name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Starwars.Grpc.sln
    - name: Build
      run: dotnet build Starwars.Grpc.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Starwars.Grpc.sln --no-restore --verbosity normal
